# Generated by Django 4.2.4 on 2023-11-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_item_transaction_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='recieved',
            new_name='received',
        ),
    ]
