# Generated by Django 4.2.4 on 2023-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('expenses', '0004_report_rename_recieved_item_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='accountinfo_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='accountinfo_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
