# Generated by Django 4.2.4 on 2023-12-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_accountinfo_groups_accountinfo_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
