# Generated by Django 4.2.4 on 2023-12-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_accountinfo_groups_accountinfo_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='is_staff',
        ),
    ]
